name: Build and Release Plugin

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Find DLL
        id: find_dll
        shell: powershell
        run: |
          $dll = Get-ChildItem -Recurse -Filter ESTClock.dll | Where-Object { $_.FullName -like "*Release*" } | Select-Object -First 1
          echo "dll_path=$($dll.FullName)" >> $env:GITHUB_OUTPUT

      - name: Prepare folder
        run: |
          mkdir release
          mkdir release/ESTClock

      - name: Copy files
        shell: powershell
        run: |
          Copy-Item "${{ steps.find_dll.outputs.dll_path }}" "release/ESTClock/ESTClock.dll"
          Copy-Item "ESTClock.json" "release/ESTClock/ESTClock.json"

      - name: Create ZIP
        run: |
          powershell Compress-Archive -Path release/ESTClock -DestinationPath ESTClock.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ESTClock.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}