name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 🔥 limpa qualquer lixo de cache / nuget quebrado
      - name: Clear NuGet
        run: dotnet nuget locals all --clear

      # 🔥 baixa Dalamud manual
      - name: Download Dalamud
        shell: powershell
        run: |
          mkdir .dalamud
          Invoke-WebRequest https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile dalamud.zip
          Expand-Archive dalamud.zip -DestinationPath .dalamud

      - name: Restore
        run: dotnet restore --no-cache

      - name: Build
        run: dotnet build -c Release --no-restore -p:DalamudLibPath="D:\a\Clock\Clock\references\"

      - name: Publish
        run: dotnet publish -c Release -o publish --no-build

      - name: Zip
        run: Compress-Archive -Path publish\* -DestinationPath Clock.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Clock.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Dalamud files
        run: dir .dalamud

      - name: Show files
        run: dir .dalamud -Recurse